[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bincode = "1.3.3"
iroh-net = { git = "https://github.com/n0-computer/iroh" }
pkarr = { git = "https://github.com/dvc94ch/pkarr", branch = "cleanup-client" }
quinn = "0.10.2"
serde = "1.0.188"
tokio = "1.32.0"

[dev-dependencies]
env_logger = "0.10.0"
log = "0.4.20"